name: Build Mod
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Просто скачиваем файлы твоего репозитория
      - name: Checkout Code
        uses: actions/checkout@v4
      
      # Проверяем и принудительно активируем уже встроенную в сервер Java 21
      - name: Use Built-in Java
        run: |
          sudo update-java-alternatives --set $(update-java-alternatives --list | grep java-1.21 | head -n 1 | awk '{print $1}') || echo "Используем текущую Java по умолчанию"
          java -version
          
      # Запускаем сборку Gradle напрямую
      - name: Build with Gradle
        run: gradle build
